### ISSUE TITLE
Webpack.config.js

### ISSUE THREAD

**Issue by ZabeehUllah** [TechStark/opencv-js#10]
Which modules are to be added in webpack.config.js and how to add modules in webpack.config.js file? I am using Reactjs.

![image](https://user-images.githubusercontent.com/22549491/163529823-19f319bc-5e2d-4c7b-9323-c0f046cd0028.png)

**Comment by ttt43ttt** [comment]
You can check the example here https://codesandbox.io/s/techstarkopencv-js-demo-page-f7gvk

**Comment by ZabeehUllah** [comment]
Can you please share a simpler boilerplate code?

**Comment by ZabeehUllah** [comment]
I already have installed the required dependency. It's still giving me the same error.

![Capture](https://user-images.githubusercontent.com/22549491/164373978-c0972956-40f3-4b19-b93c-695f25ff4359.PNG)

**Comment by ttt43ttt** [comment]
@ZabeehUllah  see https://github.com/TechStark/opencv-js#webpack-configuration-for-browser-usage for how to configure webpack

**Comment by Karthick47v2** [comment]
@ZabeehUllah  in case if you are asking for where & how to configure webpack,

1.  webpack.config.js will be in `node-modules\react-scripts\`.
2.  Search for `resolve:` in webpack, (or Search `module.exports`, `resolve` will be in return of this function)
3.  Paste the above codeblock next to `module:[.....]`

```
fallback: {
      fs: false,
      path: false,
      crypto: false
    },
```

**Comment by ZabeehUllah** [comment]
@Karthick47v2  Thank you so much. I was looking for this. Issue resolved.

**Comment by ttt43ttt** [comment]
Also see example https://github.com/TechStark/opencv-js-examples/blob/develop/opencv-js-react-example/config-overrides.js
