### ISSUE TITLE
boxPoint is not a function error

### ISSUE THREAD

**Issue by ilkertiryaki** [TechStark/opencv-js#20]
_techstark_opencv_js__WEBPACK_IMPORTED_MODULE_0__.boxPoints is not a function.

could you please help me, how can I solve this error?

**Comment by ttt43ttt** [comment]
@ilkertiryaki unfortunately it's not exposed from opencv's JS binding. See https://github.com/opencv/opencv/issues/20133

**Comment by jesseditson** [comment]
For anyone finding this in the future, this will be added to the API in OpenCV.js v4.11.0, as per https://github.com/opencv/opencv/issues/20133 (merged here: https://github.com/opencv/opencv/pull/26387). Once this package has 4.11 integrated, this will become available.
