### ISSUE TITLE
Incorrect type for minMaxLoc

### ISSUE THREAD

**Issue by pbowyer** [TechStark/opencv-js#21]
Thanks for putting together this library, it's great to have a version that can be imported and that has type support.

Now I'm using it in a strictly type-checked project I've found an incorrect type. `minMaxLoc` is reported as

```
function minMaxLoc(src: cv.Mat, minVal: any, maxVal?: any, minLoc?: any, maxLoc?: any, mask?: cv.Mat | undefined): void (+1 overload)
```

but when I use it it returns an object
```
const minMaxLoc = cv.minMaxLoc(grayImage)
```

**Comment by ttt43ttt** [comment]
Fixed in v4.8.0-release.6
