### ISSUE TITLE
Is it possible to update to OpenCV 4.7?

### ISSUE THREAD

**Issue by eldog** [TechStark/opencv-js#23]
OpenCV was released in Dec 2022 - [https://opencv.org/opencv-4-7-0/](https://opencv.org/opencv-4-7-0/)  - is it possible to update to the latest version?

I'm new to `opencv-js`, so may be not be correct on this and there may be reasons it's not possible to update the package.

**Comment by ttt43ttt** [comment]
@eldog updated
