### ISSUE TITLE
Testing issue | Jest | Vitest

### ISSUE THREAD

**Issue by vasile-encord** [TechStark/opencv-js#29]
No meter which method from the lib I call it just paralyse the test and it just stuck. Even if I try to console.log it.

```
import cv from "@techstark/opencv-js";

test("My test", () => {
    console.log(cv) // test will stuck
  },
);
```

Any ideas why it might happen?

**Comment by ttt43ttt** [comment]
See also https://github.com/TechStark/opencv-js/blob/main/test/cv.ts
