### ISSUE TITLE
how to use webpack.config.js in angular

### ISSUE THREAD

**Issue by jdbogdan** [TechStark/opencv-js#37]
Build at: 2023-08-22T08:43:25.349Z - Hash: 061d733cc768de78d388 - Time: 5986ms

./node_modules/@techstark/opencv-js/dist/opencv.js:59:34-47 - Error: Module not found: Error: Can't resolve 'fs' in '\web\node_modules\@techstark\opencv-js\dist'

./node_modules/@techstark/opencv-js/dist/opencv.js:60:38-53 - Error: Module not found: Error: Can't resolve 'path' in '\node_modules\@techstark\opencv-js\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }

Error: src/app/data-center/register-details-modal/take-photos/take-photos.component.ts:3:8 - error TS1192: Module '"E:/node_modules/@techstark/opencv-js/dist/types/index"' has no default export.

3 import cv from '@techstark/opencv-js';

**Comment by SystemR** [comment]
You need to install the custom-webpack builder.

```sh
npm install -D @angular-builders/custom-webpack
```

Then change angular.json to use the custom webpack builder instead of devkit. You can follow this article for all the steps: [https://developer.okta.com/blog/2019/12/09/angular-webpack](https://developer.okta.com/blog/2019/12/09/angular-webpack)

It should work once you've added the following `webpack.config.js`:

```js
module.exports = {
  resolve: {
    fallback: {
      fs: false,
      path: false,
      crypto: false,
    },
  },
};
```

**Comment by neodescis** [comment]
For others finding this issue, it should work to add this to package.json instead of switching to the custom-webpack builder:

```
  "browser": {
    "fs": false,
    "path": false,
    "crypto": false
  }
```

This also works with the new esbuild Angular builders.
