### ISSUE TITLE
how do I get imgproc?

### ISSUE THREAD

**Issue by mcastillo86** [TechStark/opencv-js#4]
I've just downloaded this package and I'm doing some code but I'm not able to find "Imgproc". How do I import it?

**Comment by ttt43ttt** [comment]
Not sure where "Imgproc" is used. Is it throwing an error if your testing?

**Comment by mcastillo86** [comment]
No error, I'm doing a code to change the color of certain sections of an image and for that I need Imgproc.

**Comment by mcastillo86** [comment]
I manage to workaround that, now I get a "mat.push_back is not a function" message. My code looks like this:

let mat = new cv.Mat(1, 1, cv.CV_32SC3)
mat.push_back(0, item[0]) 

where item is an array of number.

**Comment by ttt43ttt** [comment]
See document https://docs.opencv.org/3.4/de/d06/tutorial_js_basic_ops.html
I think you can try things like `mat.data[0] = item[0]`
