### ISSUE TITLE
delete() does not exist on type Mat. Necessary in this version?

### ISSUE THREAD

**Issue by keckelt** [TechStark/opencv-js#40]
Hi,
Thanks for creating this version!

I have been using  the [opencv.js file from OpenCV](https://docs.opencv.org/4.8.0/opencv.js) in JS projects previously and now using your library in a TypeScript project.

I have always been calling `.delete()` on `Mat` instances before, as they do in [tutorials on the OpenCV page](https://docs.opencv.org/4.8.0/dd/d4d/tutorial_js_image_arithmetics.html).
Is this necessary for this library as well?

I'm asking because `tsc` and VS Code are showing an error that: `Property 'delete' does not exist on type 'Mat'.ts(2339)`

**Comment by ttt43ttt** [comment]
@keckelt Thanks for pointing this out. This has been fixed in `v4.8.0-release.9`
