### ISSUE TITLE
Cannot assign to 'onRuntimeInitialized' because it is a read-only property.

### ISSUE THREAD

**Issue by chalapathi444** [TechStark/opencv-js#47]
*onRuntimeInitialized* is a read-only property., Not able to assign a function to it. Is there any way to know if the cv is initialized?
```
await new Promise<void>( 
      (resolve) =>
        (cv['onRuntimeInitialized'] = () => {
          resolve();
        });
    );
```

**Comment by Npscholar** [comment]
Hey @chalapathi444 haven't dug deep into this but have you checked this closed issue? Seems close to what you are asking #33

**Comment by ttt43ttt** [comment]
@chalapathi444 do you see the error when compiling TypeScript to JavaScript or running JavaScript code?
It should work. See https://github.com/TechStark/opencv-js/blob/main/test/cv.ts#L6

**Comment by davidjandrey-sv** [comment]
I get the same error when parcel tries to transpile & optimize my code:

> @parcel/optimizer-swc: cannot reassign to an imported binding

Also VSCode itself is warning me beforehand:

![image](https://github.com/TechStark/opencv-js/assets/100715248/6b0e695d-2f4d-47c9-a820-1c5138141927)
![image](https://github.com/TechStark/opencv-js/assets/100715248/3b140556-091d-4d13-afa8-a2586edee9ce)

**Comment by ttt43ttt** [comment]
@davidjandrey-sv which version are you using? could you provide the code/demo page to show the issue?

**Comment by davidjandrey-sv** [comment]
@ttt43ttt I'm using it for my npm package: https://www.npmjs.com/package/intellicrop
I've reproduced this issue with 4.8.0-release.4 and 4.8.0-release.10. I can try to set up a demo page for you later on, but you can see the issue if you check out my package and just try to assign a new value to the `onRuntimeInitialized` prop anywhere.

**Comment by ttt43ttt** [comment]
@davidjandrey-sv I've checked your package. Here is a way that can make it work.
- add `"esModuleInterop": true` in `tsconfig.json`
- change `import * as cv from "@techstark/opencv-js"` to `import cv from "@techstark/opencv-js"`

**Comment by davidjandrey-sv** [comment]
@ttt43ttt Yup, that worked flawless for me, thank you very much and have a nice weekend :)
