### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by sercanov** [TechStark/opencv-js#5]
There are some functions missing even they're defined in types like `solvePnPGeneric` `getVersionString` 
Did some research but not much results on internet, not surprisingly. Could it be emscripten thing?

**Comment by ttt43ttt** [comment]
@sercanov I'm not sure what's the root cause either.
I've listed all available functions here https://github.com/TechStark/opencv-js#what-methodsproerties-are-available

```js
  "solve",
  "solvePnP",
  "solvePnPRansac",
  "solvePnPRansac1",
  "solvePnPRefineLM",
  "solvePoly",
```
