### ISSUE TITLE
cv.fisheye_initUndistortRectifyMap is not found

### ISSUE THREAD

**Issue by lzcwds** [TechStark/opencv-js#51]
ts error:
Function `cv.fisheye_initUndistortRectifyMap` causes `Property 'fisheye_initUndistortRectifyMap' does not exist on type 'typeof import("xxx/node_modules/@techstark/opencv-js/dist/src/index")'.ts(2339)`
but it has output by `console.log(cv.fisheye_initUndistortRectifyMap)`

**Comment by lzcwds** [comment]
The version is `4.9.0-release.1`

**Comment by ttt43ttt** [comment]
@lzcwds added in `4.9.0-release.2`
