### ISSUE TITLE
getRectSubPix is undefined

### ISSUE THREAD

**Issue by pioz** [TechStark/opencv-js#6]
Cannot find the function [getRectSubPix](https://docs.opencv.org/4.5.4/da/d54/group__imgproc__transform.html#ga77576d06075c1a4b6ba1a608850cd614)

If I call `cv.getRectSubPix` I get undefined. This function is missing or is called with a different name?

**Comment by ttt43ttt** [comment]
@pioz you can get the available functions/properties on `cv` from https://github.com/TechStark/opencv-js#what-methodsproerties-are-available
`cv.getRectSubPix` is not exposed to JS module.
