### ISSUE TITLE
global persistence.cpp:519 open Can't open file: 'haarcascade_frontalface_alt.xml' in read mode

### ISSUE THREAD

**Issue by Banqc0621** [TechStark/opencv-js#63]
### 方式1：

```
const haarcascades_path = "D:\\models\\data\\haarcascades\\haarcascade_frontalface_alt.xml";

 // 加载人脸检测器模型（模型已经存在）
 const faceCascade = new this.$cv.CascadeClassifier(haarcascades_path);
```

### 方式2：
```
   const haarcascades_path = "D:\\models\\data\\haarcascades\\haarcascade_frontalface_alt.xml";
   // 加载人脸检测器模型（模型已经存在）
  const faceCascade = new this.$cv.CascadeClassifier();
  console.log("dsfsdf", faceCascade.load(haarcascades_path));
```

以上两种方式加载模型均报错误：
![1094c774297121b33f48b6b738ef703](https://github.com/TechStark/opencv-js/assets/98104475/9661d23c-ef06-44e4-b54d-8e492bddacd8)

已经尝试过相对路径，绝对路径，路径无中文。始终都是报无法读取的问题。缓存也都清除。

https://forum.opencv.org/t/global-persistence-cpp-505-open-cant-open-file-in-read-mode/12581/20
找到这篇贴子，从实际上也没有效果，本质上还是加载文件。

该页完整程序如下：

```
<template>
  <div class="container">
    <!-- 背景容器 -->
    <div class="picture" :style="{ backgroundImage: 'url(' + originalBackgroundUrl + ')', backgroundPosition: 'center' }">
      <!-- 图片输入区域 -->
      <div class="image-input-container">
        <!-- Unicode输入框 -->
        <input class="image-url" v-model="input1" @blur="updateBackground" placeholder="请输入网络图片URL" />
        <!-- 本地上传图片按钮 -->
        <button class="image-upload" @click="openImageSelector">本地上传</button>
        <!-- 检测按钮 -->
        <button class="image-detection">处理</button>
      </div>
    </div>
    <!-- 本地图片展示区域 -->
    <div class="local-images">
      <img
        v-for="(image, index) in localImages"
        :src="image"
        :key="index"
        @click="changeBackground(index + 1)"
        style="background-position: top right"
      />
    </div>
    <!-- 识别结果展示区域 -->
    <div class="detection-result">
      <div class="column-header" @click="showContent('识别结果')">处理结果</div>
      <div class="column-content">
        <el-input placeholder="处理结果文件" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.recognize" :disabled="false"></el-input>
        <el-input placeholder="对比可得" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.character" :disabled="false"></el-input>
        <el-input placeholder="为" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.characterCategory" :disabled="false"></el-input>
        {{ ocrResult }}
      </div>
    </div>
    <!-- Loading overlay -->
    <div class="loading-overlay" v-if="loading">
      <div class="loading-spinner"></div>
    </div>
  </div>
</template>

<script>
import originalBackgroundUrl from "@/assets/images/portrait/init.jpg";

export default {
  data() {
    return {
      input1: "",
      localImages: [],
      originalBackgroundUrl: originalBackgroundUrl,
      loading: false,
      ocrResult: "",
      input: "",
      result: {
        recognize: null,
        character: null,
        characterCategory: null
      }
    };
  },
  created() {
    this.loadLocalImages();
  },
  methods: {
    openImageSelector() {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = "image/*";
      input.onchange = event => {
        const file = event.target.files[0];
        const reader = new FileReader();
        reader.onload = event => {
          this.originalBackgroundUrl = event.target.result;
        };
        reader.readAsDataURL(file);
      };
      input.click();
    },

    async changeBackground(index) {
      this.loading = true;
      this.originalBackgroundUrl = this.loadSelectImage(index);
      await this.faceSegmentation(this.originalBackgroundUrl);
      this.loading = false;
    },

    async faceSegmentation(imageUrl) {
      try {
        const imgElement = new Image();
        imgElement.src = imageUrl;

        const canvas = document.createElement("canvas");
        const context = canvas.getContext("2d");

        await new Promise((resolve, reject) => {
          imgElement.onload = resolve;
          imgElement.onerror = reject;
        });
        canvas.width = imgElement.width;
        canvas.height = imgElement.height;

        context.drawImage(imgElement, 0, 0, canvas.width, canvas.height);

        const img = await this.$cv.imread(canvas);
        const haarcascades_path = "D:\\models\\data\\haarcascades\\haarcascade_frontalface_alt.xml";

        // 加载人脸检测器模型（假设模型已经存在）
        const faceCascade = new this.$cv.CascadeClassifier(haarcascades_path);

        console.log(faceCascade);

        const faces = new this.$cv.RectVector();
        const faceSize = new this.$cv.Size(0, 0);

        faceCascade.detectMultiScale(img, faces, 1.1, 3, 0, faceSize, faceSize);

        const faceRect = faces.get(0);
        const x = faceRect.x;
        const y = faceRect.y;
        const w = faceRect.width;
        const h = faceRect.height;

        const eyeRect = new this.$cv.Rect(x + w * 0.2, y + h * 0.2, w * 0.25, h * 0.15);
        const noseRect = new this.$cv.Rect(x + w * 0.35, y + h * 0.4, w * 0.3, h * 0.25);
        const mouthRect = new this.$cv.Rect(x + w * 0.2, y + h * 0.65, w * 0.6, h * 0.3);

        const eyeImg = img.roi(eyeRect);
        const noseImg = img.roi(noseRect);
        const mouthImg = img.roi(mouthRect);

        console.log("eyeImg", eyeImg);
        console.log("noseImg", noseImg);
        console.log("mouthImg", mouthImg);
        img.delete();
        eyeImg.delete();
        noseImg.delete();
        mouthImg.delete();
      } catch (error) {
        console.error("Face segmentation error:", error);
      }
    },

    loadLocalImages() {
      const images = [];
      for (let i = 1; i <= 5; i++) {
        images.push(this.loadSelectImage(i));
      }
      this.localImages = images;
    },
    loadSelectImage(index) {
      return new URL(`../../../../assets/images/portrait/0${index}.jpg`, import.meta.url).href;
    },
    updateCharacter(unicodeInput) {
      const input = unicodeInput || "";
      const unicodeMatches = input.match(/U\+[0-9A-Fa-f]{4}/g);
      if (unicodeMatches) {
        const unicodeArray = unicodeMatches.map(match => {
          return String.fromCodePoint(parseInt(match.slice(2), 16));
        });
        return unicodeArray.join("");
      } else {
        return "";
      }
    },
    updateBackground() {
      this.originalBackgroundUrl = this.input1.trim();
    }
  }
};
</script>

<style scoped>
.container {
  position: relative;
  justify-content: center;
  width: 86%;
  height: 100%;
  margin: auto;
  text-align: center;
}
.picture {
  position: relative;
  width: 60%;
  height: 80%;
  background-position: center;
  background-size: cover; /* 使用 cover 或 contain */
}
.detection-result {
  position: absolute;
  top: 0;
  right: 0;
  width: 25%;
  height: 100%;
  overflow: auto;
  background-color: #f0f0f0;
}
.column-header {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 20px;
  font-weight: bold;
  cursor: pointer;
}
.column-content {
  font-family: "Microsoft YaHei";
  font-size: 15px;
}
.image-input-container {
  position: absolute;
  bottom: 0;
  left: 0;
  z-index: 9;
  box-sizing: border-box;
  width: 100%;
  padding: 8px 10px;
  background: rgb(0 0 0 / 50%);
}
.image-notice {
  margin-top: 10px;
  font-size: 12px;
  color: #cccccc;
  text-align: center;
}
.image-url {
  display: inline-block;
  width: 65%;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  text-indent: 12px;
  background-color: rgb(0 0 0 / 45%);
  border: 1px solid #666666;
}
.image-upload {
  display: inline-block;
  min-width: 15%;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  background-color: rgb(0 0 0 / 45%);
  border: 1px solid #666666;
}
.image-detection {
  display: inline-block;
  min-width: 15%;
  margin-left: 20px;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  background-color: #0073eb;
  border: 1px solid #666666;
}
.image-upload:hover,
.image-detection:hover {
  cursor: pointer;
  background-color: rgb(0 0 0 / 55%);
}
.local-images {
  position: absolute;
  top: 80%;
  left: 30%;
  display: flex;
  align-items: center;
  background-color: #ebebeb;
  transform: translateX(-50%);
}
.local-images img {
  width: 100px; /* 设置显示尺寸 */
  height: 70px; /* 设置显示尺寸 */
  background-color: rgb(0 0 0 / 49%);
  background-position: top right;
  border: 2px solid #cccccc;
  transition: border-color 0.3s ease-in-out;
  object-fit: cover; /* 图像大小不变，自动裁剪以填充容器 */
  object-position: center center; /* 图像内容居中 */
}
.local-images img:hover {
  cursor: pointer;
  border-color: rgb(121 113 113);
}

/* 加载中效果 */
.loading-overlay {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgb(255 255 255 / 70%);
}
.loading-spinner {
  width: 50px;
  height: 50px;
  border: 5px solid #f3f3f3;
  border-top: 5px solid #3498db;
  border-radius: 50%;
  animation: spin 2s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>

```

**Comment by ttt43ttt** [comment]
This is running in the browser. It doesn't have access to your local file system.
You can download the model file from a URL. See example here https://github.com/TechStark/opencv-js-examples/blob/develop/opencv-js-react-example/src/opencv/haarFaceDetection.js#L7

**Comment by Banqc0621** [comment]
非常感谢您的指导！目前已经解决。
![image](https://github.com/TechStark/opencv-js/assets/98104475/a91c9c54-793a-4170-9c42-ae1d3ac4c454)

成功代码如下：
`<template>
  <div class="container">
    
    <div class="picture" :style="{ backgroundImage: 'url(' + originalBackgroundUrl + ')', backgroundPosition: 'center' }">
      
      <div class="image-input-container">
        
        <input class="image-url" v-model="input1" @blur="updateBackground" placeholder="请输入网络图片URL" />
        
        <button class="image-upload" @click="openImageSelector">本地上传</button>
        
        <button class="image-detection" @click="detectFaces">处理</button>
      </div>
    </div>
    
    <div class="local-images">
      <img
        v-for="(image, index) in localImages"
        :src="image"
        :key="index"
        @click="changeBackground(index + 1)"
        style="background-position: top right"
      />
    </div>
    
    <div class="detection-result">
      <div class="column-header" @click="showContent('识别结果')">处理结果</div>
      <div class="column-content">
        <el-input placeholder="处理结果文件" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.recognize" :disabled="false"></el-input>
        <el-input placeholder="对比可得" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.character" :disabled="false"></el-input>
        <el-input placeholder="为" :disabled="true"></el-input>
        <el-input placeholder="" v-model="result.characterCategory" :disabled="false"></el-input>
        {{ ocrResult }}
      </div>
    </div>
    
    <div class="loading-overlay" v-if="loading">
      <div class="loading-spinner"></div>
    </div>
  </div>
</template>

<script>
import originalBackgroundUrl from "@/assets/images/portrait/init.jpg";

export default {
  data() {
    return {
      input1: "",
      localImages: [],
      originalBackgroundUrl: originalBackgroundUrl,
      loading: false,
      ocrResult: "",
      input: "",
      result: {
        recognize: null,
        character: null,
        characterCategory: null
      }
    };
  },
  created() {
    this.loadLocalImages();
    this.loadHaarFaceModels();
  },
  methods: {
    // 打开文件选择器以选择本地图片
    openImageSelector() {
      const input = document.createElement("input");
      input.type = "file";
      input.accept = "image/*";
      input.onchange = event => {
        const file = event.target.files[0];
        const reader = new FileReader();
        reader.onload = event => {
          this.originalBackgroundUrl = event.target.result;
        };
        reader.readAsDataURL(file);
      };
      input.click();
    },

    // 更改背景图片
    async changeBackground(index) {
      this.loading = true;
      this.originalBackgroundUrl = this.loadSelectImage(index);
      await this.faceSegmentation(this.originalBackgroundUrl);
      this.loading = false;
    },

    // 加载Haar级联模型
    async loadHaarFaceModels() {
      try {
        console.log("=======开始下载Haar级联模型=======");
        await this.loadDataFile("haarcascade_frontalface_default.xml", "models/haarcascade_frontalface_default.xml");
        await this.loadDataFile("haarcascade_eye.xml", "models/haarcascade_eye.xml");
        console.log("=======Haar级联模型下载完成=======");
      } catch (error) {
        console.error(error);
      }
    },

    // 加载数据文件
    async loadDataFile(cvFilePath, url) {
      const response = await fetch(url);
      const buffer = await response.arrayBuffer();
      const data = new Uint8Array(buffer);
      this.$cv.FS_createDataFile("/", cvFilePath, data, true, false, false);
    },

    // 检测人脸
    detectHaarFace(img) {
      const newImg = img.clone();
      const gray = new this.$cv.Mat();
      this.$cv.cvtColor(newImg, gray, this.$cv.COLOR_RGBA2GRAY, 0);
      const faces = new this.$cv.RectVector();
      const eyes = new this.$cv.RectVector();
      const faceCascade = new this.$cv.CascadeClassifier();
      const eyeCascade = new this.$cv.CascadeClassifier();
      faceCascade.load("haarcascade_frontalface_default.xml");
      eyeCascade.load("haarcascade_eye.xml");
      const msize = new this.$cv.Size(0, 0);
      faceCascade.detectMultiScale(gray, faces, 1.1, 3, 0, msize, msize);
      for (let i = 0; i < faces.size(); ++i) {
        const roiGray = gray.roi(faces.get(i));
        const roiSrc = newImg.roi(faces.get(i));
        const point1 = new this.$cv.Point(faces.get(i).x, faces.get(i).y);
        const point2 = new this.$cv.Point(faces.get(i).x + faces.get(i).width, faces.get(i).y + faces.get(i).height);
        this.$cv.rectangle(newImg, point1, point2, [255, 0, 0, 255]);
        eyeCascade.detectMultiScale(roiGray, eyes);
        for (let j = 0; j < eyes.size(); ++j) {
          const point1 = new this.$cv.Point(eyes.get(j).x, eyes.get(j).y);
          const point2 = new this.$cv.Point(eyes.get(j).x + eyes.get(j).width, eyes.get(j).y + eyes.get(j).height);
          this.$cv.rectangle(roiSrc, point1, point2, [0, 0, 255, 255]);
        }
        roiGray.delete();
        roiSrc.delete();
      }
      gray.delete();
      faceCascade.delete();
      eyeCascade.delete();
      faces.delete();
      eyes.delete();
      return newImg;
    },

    // 人脸分割处理
    async faceSegmentation(imageUrl) {
      try {
        const imgElement = new Image();
        imgElement.src = imageUrl;
        const canvas = document.createElement("canvas");
        const context = canvas.getContext("2d");
        await new Promise((resolve, reject) => {
          imgElement.onload = resolve;
          imgElement.onerror = reject;
        });
        canvas.width = imgElement.width;
        canvas.height = imgElement.height;
        context.drawImage(imgElement, 0, 0, canvas.width, canvas.height);
        const img = await this.$cv.imread(canvas);
        console.log("开始人脸检测");
        const haarFaces = this.detectHaarFace(img);

        // 将处理后的图像转换为DataURL
        this.$cv.imshow(canvas, haarFaces);
        const processedImageUrl = canvas.toDataURL();

        // 更新背景图片URL
        this.originalBackgroundUrl = processedImageUrl;

        img.delete();
        haarFaces.delete();
      } catch (error) {
        console.error("人脸分割错误:", error);
      }
    },

    // 调用人脸检测
    detectFaces() {
      this.faceSegmentation(this.originalBackgroundUrl);
    },

    // 加载本地图片
    loadLocalImages() {
      const images = [];
      for (let i = 1; i <= 5; i++) {
        images.push(this.loadSelectImage(i));
      }
      this.localImages = images;
    },

    // 加载选择的图片
    loadSelectImage(index) {
      return new URL(`../../../../assets/images/portrait/0${index}.jpg`, import.meta.url).href;
    },

    // 更新背景图片
    updateBackground() {
      this.originalBackgroundUrl = this.input1.trim();
    }
  }
};
</script>

<style scoped>
.container {
  position: relative;
  justify-content: center;
  width: 86%;
  height: 100%;
  margin: auto;
  text-align: center;
}
.picture {
  position: relative;
  width: 60%;
  height: 80%;
  background-position: center;
  background-size: cover;
}
.detection-result {
  position: absolute;
  top: 0;
  right: 0;
  width: 25%;
  height: 100%;
  overflow: auto;
  background-color: #f0f0f0;
}
.column-header {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 20px;
  font-weight: bold;
  cursor: pointer;
}
.column-content {
  font-family: "Microsoft YaHei";
  font-size: 15px;
}
.image-input-container {
  position: absolute;
  bottom: 0;
  left: 0;
  z-index: 9;
  box-sizing: border-box;
  width: 100%;
  padding: 8px 10px;
  background: rgb(0 0 0 / 50%);
}
.image-notice {
  margin-top: 10px;
  font-size: 12px;
  color: #cccccc;
  text-align: center;
}
.image-url {
  display: inline-block;
  width: 65%;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  text-indent: 12px;
  background-color: rgb(0 0 0 / 45%);
  border: 1px solid #666666;
}
.image-upload {
  display: inline-block;
  min-width: 15%;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  background-color: rgb(0 0 0 / 45%);
  border: 1px solid #666666;
}
.image-detection {
  display: inline-block;
  min-width: 15%;
  margin-left: 20px;
  font-size: 10px;
  line-height: 36px;
  color: #cccccc;
  background-color: #0073eb;
  border: 1px solid #666666;
}
.image-upload:hover,
.image-detection:hover {
  cursor: pointer;
  background-color: rgb(0 0 0 / 55%);
}
.local-images {
  position: absolute;
  top: 80%;
  left: 30%;
  display: flex;
  align-items: center;
  background-color: #ebebeb;
  transform: translateX(-50%);
}
.local-images img {
  width: 100px;
  height: 70px;
  background-color: rgb(0 0 0 / 49%);
  background-position: top right;
  border: 2px solid #cccccc;
  transition: border-color 0.3s ease-in-out;
  object-fit: cover;
  object-position: center center;
}
.local-images img:hover {
  cursor: pointer;
  border-color: #797171;
}
.loading-overlay {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgb(255 255 255 / 70%);
}
.loading-spinner {
  width: 50px;
  height: 50px;
  border: 5px solid #f3f3f3;
  border-top: 5px solid #3498db;
  border-radius: 50%;
  animation: spin 2s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
`
