### ISSUE TITLE
Reduce the size of the dependency

### ISSUE THREAD

**Issue by ieleg** [TechStark/opencv-js#70]
I am using version 4.9.0-release.3 in a browser environment with Vite bundling. There is a base64 file in the browser network that is almost 7.5MB in size and has the format octet-stream. How can I reduce the size of the dependency?
![image](https://github.com/TechStark/opencv-js/assets/52823905/a6ba36c6-0a2c-4d94-ab2b-d3d5d4275191)

**Comment by ttt43ttt** [comment]
You can enable compression (e.g. gzip) on the server side to reduce the network transfer size. However, reducing the size of this library is not a plan.
