### ISSUE TITLE
rollup config please

### ISSUE THREAD

**Issue by cfry** [TechStark/opencv-js#72]
I was using a quite old version of opencv.js and was delighted to see this newer version..
I'm running in the browser and am using rollup.
While loading my web page, I get the error:
**Uncaught TypeError: Failed to resolve module specifier "fs". Relative references must start with either "/", "./", or "../".**

In your readme file, you have a webpack configuration of:
```
module.exports = {
  resolve: {
    modules: [...],
    fallback: {
      fs: false,
      path: false,
      crypto: false
    }
  }
};
```
but I'm not fluent enough to convert that to rollup.
It would really heap me if you could supply a rollup version.
I'm guessing this would be a nice addition to your readme file for others too.
Thanks so much!

**Comment by ttt43ttt** [comment]
@cfry see https://github.com/TechStark/opencv-js-examples/blob/develop/opencv-js-rollup-example/rollup.config.js
