### ISSUE TITLE
run inpaint throw error 

### ISSUE THREAD

**Issue by appLhui** [TechStark/opencv-js#8]
![image](https://user-images.githubusercontent.com/3120584/160993618-d5c8cb36-d95b-447e-9045-53ee438c0873.png)

![image](https://user-images.githubusercontent.com/3120584/160993685-245dbb99-dc88-43d0-ae6a-64c0fd2a3aa8.png)

**Comment by ttt43ttt** [comment]
it seems this is thrown from opencv itself. not an issue that can be resolved in this repo.
